# Generated by Django 3.1.4 on 2022-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220525_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='group',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
