# Generated by Django 3.1.4 on 2022-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20220529_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakturaitem',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdan_cgiqarish_filial',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hisobdanchiqarishombor',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productfilial',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qaytganproductombor',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiveitem',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yetkazilgantavar',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
