# Generated by Django 3.1.4 on 2022-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20220530_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaytganproductombor',
            name='farqi_dollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaytganproductombor',
            name='farqi_som',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
