# Generated by Django 3.1.4 on 2022-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220530_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='arrival_price_som',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='selling_price_som',
            field=models.FloatField(default=0),
        ),
    ]
