# Generated by Django 3.1.4 on 2022-07-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20220531_0945'),
        ('api', '0048_auto_20220531_0942'),
    ]

    operations = [
    ]
